### ISSUE TITLE
Your README mentions the MIT license, but the LICENSE file is Apache

### ISSUE THREAD

**Issue by parker-research** [rocksavagetech/dynamicfifo#3]
Huge fan of this work!

Just wanted to note that you have inconsistent licensing.

Have you considered using a license designed specifically for hardware; for example, the [CERN Open Hardware Licence Version 2 - Permissive (CERN OHL v2 Permissive)](https://choosealicense.com/licenses/cern-ohl-p-2.0/) license?

**Comment by twsavage59** [comment]
Yes, I have to fix that.  I polled a bunch of people I respect, including our lawyer and the consensus was Apache2. I had planned all along for MIT, but was convinced at the last minute to change. But I will look into that CERN license, I hadn't heard of it!

**Comment by twsavage59** [comment]
Fixed, thanks for catching that.  Also, there was a mention of dependencies which was also outdated information.

**Comment by parker-research** [comment]
No worries, happy to help! :)

**Comment by maliberty** [comment]
close?

**Comment by twsavage59** [comment]
Yes, fixed with cdf7f00 commit back in June.

**Comment by twsavage59** [comment]
Issue closed.
